#ifndef GCS_MAVLINK_NODE_H
#define GCS_MAVLINK_NODE_H

#include <udp/simple_udp.h>

#include <app_config.h>
#include <ardupilotmega/mavlink.h>
#include <gcs_ui_types.h>

#include <atomic>
#include <chrono>
#include <cstdint>
#include <deque>
#include <mutex>

/**
 * High-level mode requests triggered by the dashboard.
 */
enum class RequestedMode : uint32_t {
	GuidedDisarmed = 0,
	GuidedArmed = 1,
	Land = 2,
};

/**
 * Supported outbound command types sent from the GCS to the drone.
 */
enum class PendingCommandType {
	ModeChange,
	OverrideGoto,
};

/**
 * Queued command data shared between the GUI thread and the MAVLink thread.
 */
struct PendingCommand {
	PendingCommandType type = PendingCommandType::ModeChange;
	RequestedMode mode = RequestedMode::GuidedDisarmed;
	XYPoint target{};
	float target_altitude_ned_m = 0.0f;
};

/**
 * Current manual-control intent generated by the dashboard.
 */
struct TeleopState {
	bool enabled = false;
	float x_velocity_mps = 0.0f;
	float y_velocity_mps = 0.0f;
	float z_velocity_mps = 0.0f;
};

/**
 * MAVLink identifiers used by the ground control station.
 */
struct GcsMavlinkIds {
	uint8_t gcs_system_id = 255;
	uint8_t gcs_component_id = MAV_COMP_ID_SYSTEM_CONTROL;
	uint8_t drone_system_id = 1;
	uint8_t drone_component_id = MAV_COMP_ID_AUTOPILOT1;
};

/**
 * Owns the MAVLink/UDP communication loop for the GCS and exposes
 * thread-safe dashboard state and callbacks.
 */
class GcsMavlinkNode {
public:
	GcsMavlinkNode(
		const SharedConfig& shared_config,
		const GcsConfig& gcs_config,
		const DroneConfig& drone_config,
		std::atomic_bool& running);

	/** Runs the blocking MAVLink worker loop until shutdown is requested. */
	void run();

	/** Builds a snapshot used to render the dashboard for the current frame. */
	[[nodiscard]] gcs_ui::DashboardState makeDashboardState() const;

	/** Creates dashboard callbacks that enqueue commands for the worker loop. */
	[[nodiscard]] gcs_ui::DashboardActions makeDashboardActions();

private:
	[[nodiscard]] const char* modeLabel(RequestedMode mode) const;
	void queueModeCommand(RequestedMode mode);
	void setTeleopEnabled(bool enabled);
	void updateTeleopAxes(float x_axis, float y_axis, float z_axis);
	[[nodiscard]] TeleopState getTeleopState() const;
	[[nodiscard]] bool queueOverrideGotoCommand(float x, float y, float altitude_m);
	[[nodiscard]] bool popPendingCommand(PendingCommand& command);

	void updateHeartbeat(const mavlink_message_t& msg);
	void updateLocalPosition(const mavlink_message_t& msg);
	void updateGeofencePoint(const mavlink_message_t& msg);
	void handleMavlinkMessage(const mavlink_message_t& msg);
	[[nodiscard]] bool nextMissingGeofenceIndex(uint8_t& index) const;

	void sendSetModeCommand(UdpSocket& socket, RequestedMode mode) const;
	void sendOverrideGotoCommand(UdpSocket& socket, const XYPoint& target, float target_altitude_ned_m) const;
	void sendGeofenceFetchRequest(UdpSocket& socket, uint8_t point_index) const;
	void sendManualControl(UdpSocket& socket, const TeleopState& teleop_state) const;
	void requestGeofenceIfNeeded(UdpSocket& socket, const std::chrono::steady_clock::time_point& now);

	const SharedConfig& shared_config_;
	const GcsConfig& gcs_config_;
	const DroneConfig& drone_config_;
	std::atomic_bool& running_;
	IpAddress drone_addr_{};
	GcsMavlinkIds ids_{};

	mutable std::mutex telemetry_mutex_;
	mutable std::mutex command_mutex_;
	mutable std::mutex teleop_mutex_;
	std::deque<PendingCommand> pending_commands_;
	TeleopState teleop_state_{};
	gcs_ui::TelemetrySnapshot telemetry_{};
	std::chrono::steady_clock::time_point last_geofence_request_time_{};
};

#endif // GCS_MAVLINK_NODE_H
